import type { Settings } from './types';

export const emptySettings: Settings = {
  language: 'ru',
  projects_folder: '',
  sandboxes_folder: '',
  package_manager: 'pnpm',
  port_start: 3000,
  port_end: 3999,
  open_preview_automatically: true,
  start_minimized: false,
  launch_on_startup: false,
  use_bundled_node: true,
  node_path: '',
  npm_path: '',
  pnpm_path: '',
  yarn_path: '',
  bun_path: '',
  php_path: '',
  git_path: '',
  use_turbopack: false,
  clear_next_before_start: false,
  enable_network_preview: true,
  enable_https: false,
  default_next_port: 3000,
  default_device: 'Desktop',
  desktop_width: 1440,
  laptop_width: 1280,
  tablet_width: 768,
  mobile_width: 390,
  custom_width: 980,
  auto_reload_preview: true,
  open_external_browser_on_start: false,
  environment_variables: '',
  hosts: '',
  ssl_certificates: '',
  proxy_rules: '',
  process_timeout: 60,
  log_retention: 14,
};
